apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-qpn1
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0051-tenant/tkrw-pr712-0075-0051-app/devfile-sample-qpn1@sha256:1092fa4022e517517a86ce7c7eed10982ac2844477cf9863f1acaec77efcf023
        name: my-nodejs
        resources: {}
status: {}
